import Head from 'next/head';
import Image from 'next/image';
import BaseLayout from '@/components/layouts/BaseLayout.js';
import styles from '../styles/Home.module.css';
import PortfolioCard from './../components/portfolios/PortfolioCard';
import TopicLink from './../components/Forums/TopicLink';
import Link from 'next/link.js';
import { useGetHighlight } from '@/apollo/actions/index';
import client from '@/apollo/apollo-client.js';
import { GET_HIGHLIGHT } from '@/apollo/queries/forum.js';

const useGetInitialData = async () => {
  const data = await useGetHighlight({ variables: { limit: 3 } });
  console.log('Data retrned:', data);
  const portfolios = (data && data.highlight.portfolios) || [];
  const topics = (data && data.highlight.topics) || [];
  return { portfolios, topics };
};

export async function getStaticProps() {
  const { data } = await client.query({
    query: GET_HIGHLIGHT,
    variables: { limit: 3 },
  });
  const trans = data.highlight;

  return { props: { trans } };
}

export default function Home(props) {
  // const { topics, portfolios } = useGetInitialData();

  const { portfolios, topics } = props.trans;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BaseLayout page="Home">
        <section className="section-title">
          <div className="px-2">
            <div className="pt-5 pb-4">
              <h1>Portfolio</h1>
            </div>
          </div>
        </section>

        <section className="pb-5">
          <div className="row">
            {portfolios.map((portfolio) => (
              <div key={portfolio._id} className="col-md-4">
                <Link
                  href="/portfolios/[id]"
                  // as={`/portfolios/${portfolio._id}`}
                >
                  <PortfolioCard portfolio={portfolio} />
                </Link>
              </div>
            ))}
          </div>
        </section>
        <Link href="/portfolios">See more Portfolios</Link>
        <section className="section-title">
          <div className="px-2">
            <div className="pt-5 pb-4">
              <h1>Ask Me</h1>
            </div>
          </div>
        </section>
        <section className="pb-5">
          <div className="list-group">
            {topics.map((topic) => (
              <TopicLink key={topic._id} topic={topic} />
            ))}
          </div>
        </section>
        <Link href="/forum/categories">See More Posts</Link>
      </BaseLayout>
    </div>
  );
}
